### ISSUE TITLE
Possibility to get output in stdout

### ISSUE THREAD

**Issue by ekkinox** [peetya/snipforge-cli#2]
I wonder if it would be possible (if not already the case) to have the possibility to get output directly in stdout, so when you're in a coding session you dont have to leave your current work and open another file.

In addition, you could use [glamour](https://github.com/charmbracelet/glamour) to colorize such stdout snippets (if you ask AI to generate in ususal markdown format), it makes it even fancier :)

**Comment by peetya** [comment]
You can already use the `--stdout` flag to achieve it :)

For example:
```bash
$ snipforge --goal "Hello World script" --language Golang --openai-key "..." --stdout > my_snippet.go
```
